name: exam_flutter
description: BadWallet Mobile Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Networking
  http: ^1.1.0
  dio: ^5.4.0
  
  # Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  
  # UI
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  
  # Utils
  intl: ^0.18.1
  connectivity_plus: ^5.0.2
  
  # Icons
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/badwallet_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/badwallet_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/